import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Providers";
import Provider from "./trpc/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter as FontSans } from "next/font/google";
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='fontSans.variable'>
        <Provider>
          <Providers>{children}</Providers>
        </Provider>
      </body>
    </html>
  );
}
